version: '3.9'

services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: postgis-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gis_db
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data
    networks:
      - gis-net

  python:
    build:
      context: ./python
    container_name: python-gis
    command: sh      
    tty: true         
    stdin_open: true   
    volumes:
      - ./python:/workspace
    networks:
      - gis-net
    depends_on:
      - postgis

volumes:
  postgis-data:

networks:
  gis-net:
    driver: bridge
