version: '3.9'

services:
  postgis:
    platform: linux/amd64
    build:
      context: ./postgis
    container_name: postgis-db
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data
      - ./postgis/data/:/data
    networks:
      - gis-net

  python:
    build:
      context: ./python
    container_name: python-gis
    command: sh      
    tty: true         
    stdin_open: true   
    volumes:
      - ./python:/workspace
    networks:
      - gis-net
    depends_on:
      - postgis
    ports:
      - "8888:8888"

volumes:
  postgis-data:
    driver: local

networks:
  gis-net:
    driver: bridge
